// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gllffexjqromdcqgoeec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsbGZmZXhqcXJvbWRjcWdvZWVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMzUxOTcsImV4cCI6MjA1NTkxMTE5N30.ufLiVCLNM8pXNT2dleTM6u2Vgt5Q7vDYM8WAlXjUE5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);